stages:
  - build
  - deploy

build project:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

netlify:
  stage: deploy
  image: node:14
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod